main:
  - name: Art
    pageRef: art
    weight: 10
  - name: Notes
    pageRef: notes
    weight: 20
  - name: github
    url: https://github.com/bdazl/peyron.io
    weight: 100
    params:
      icon: github
      showName: false
      target: _blank
